#!/usr/bin/env php
<?php 
/*
 *---------------------------------------------------------------
 * Pure php webserver
 *---------------------------------------------------------------
 *
 * This is the source code for the tutorial:
 */

use davelip\NTLM\Proxy\Proxy; 
use davelip\NTLM\Proxy\Server; 
use davelip\NTLM\Proxy\Request;
use davelip\NTLM\Proxy\Response;

require 'vendor/autoload.php';

// we never need the first argument
array_shift( $argv );

// the next argument should be the port if not use 80
if ( empty( $argv ) )
{
	$port = 8445;
} else {
	$port = array_shift( $argv );
}

// create a new server instance
$server = new Server( '127.0.0.1', $port );

function addlog ($message="") {
  error_log("[" . date("Y-m-d H:i:s") . "] " . $message . PHP_EOL, 3, "/tmp/server.log");
}

addlog('parto');

// start listening
$server->listen( function( Request $request, Proxy $proxy ) 
{
addlog('arriva');
	// print information that we recived the request
	echo $request->type() . ' ' . $request->sessionId() . ' ' . $request->param() . "\n";

	if ($request->type()=='type1') {
    		$r = base64_encode($proxy->negotiate(base64_decode($request->param())));
    		return new Response($r);
	} else {
    		$r = base64_encode(($proxy->handleType3(base64_decode($request->param())) ? 'valid' : 'invalid'));
    		return new Response($r);
	}
});
