#!/usr/bin/env php
<?php 
/*
 *---------------------------------------------------------------
 * Pure php webserver
 *---------------------------------------------------------------
 *
 * This is the source code for the tutorial:
 */

use davelip\NTLM\Proxy\Proxy; 
use davelip\NTLM\Proxy\Server; 
use davelip\NTLM\Proxy\Request;
use davelip\NTLM\Proxy\Response;

require 'vendor/autoload.php';

// we never need the first argument
array_shift( $argv );

// the next argument should be the port if not use 80
if ( empty( $argv ) )
{
	$port = 8445;
} else {
	$port = array_shift( $argv );
}

// create a new server instance
$server = new Server( '127.0.0.1', $port );

// start listening
$server->listen( function( Request $request ) 
{
	// print information that we recived the request
	echo $request->type() . ' ' . $request->sessionId() . ' ' . $request->message() . "\n";
	
    $a = new Proxy();

    return new Response( base64_encode($a->negotiate(base64_decode($request->message()))));
});
